<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $city = [
            ['name' => 'Alto Orinoco (La Esmeralda)','state_id' => 1],
            ['name' => 'Atabapo (San Fernando de Atabapo)','state_id' => 1],
            ['name' => 'Atures (Puerto Ayacucho)','state_id' => 1],
            ['name' => 'Autana (Isla Ratón)','state_id' => 1],
            ['name' => 'Manapiare (San Juan de Manapiare)','state_id' => 1],
            ['name' => 'Maroa (Maroa)','state_id' => 1],
            ['name' => 'Río Negro (San Carlos de Río Negro)','state_id' => 1],
            ['name' => 'Anaco (Anaco)','state_id' => 2],
            ['name' => 'Aragua (Aragua de Barcelona)','state_id' => 2],
            ['name' => 'Bolívar (Barcelona)','state_id' => 2],
            ['name' => 'Bruzual (Clarines)','state_id' => 2],
            ['name' => 'Cajigal (Onoto)','state_id' => 2],
            ['name' => 'Carvajal (Valle de Guanape)','state_id' => 2],
            ['name' => 'Diego Bautista Urbaneja (Lechería)','state_id' => 2],
            ['name' => 'Freites (Cantaura)','state_id' => 2],
            ['name' => 'Guanipa (San José de Guanipa)','state_id' => 2],
            ['name' => 'Guanta (Guanta)','state_id' => 2],
            ['name' => 'Independencia (Soledad)','state_id' => 2],
            ['name' => 'Libertad (San Mateo)','state_id' => 2],
            ['name' => 'McGregor (El Chaparro)','state_id' => 2],
            ['name' => 'Miranda (Pariaguán)','state_id' => 1],
            ['name' => 'Monagas (San Diego de Cabrutica)','state_id' => 1],
            ['name' => 'Peñalver (Puerto Píritu)','state_id' => 1],
            ['name' => 'Píritu (Píritu)','state_id' => 2],
            ['name' => 'San Juan de Capistrano (Boca de Uchire)','state_id' => 2],
            ['name' => 'Santa Ana (Santa Ana)','state_id' => 2],
            ['name' => 'Simón Rodriguez (El Tigre)','state_id' => 2],
            ['name' => 'Sotillo (Puerto La Cruz)','state_id' => 2],
            ['name' => 'Achaguas (Achaguas)','state_id' => 3],
            ['name' => 'Biruaca (Biruaca)','state_id' => 3],
            ['name' => 'Muñoz (Bruzual)','state_id' => 3],
            ['name' => 'Páez (Guasdualito)','state_id' => 3],
            ['name' => 'Pedro Camejo (San Juan de Payara)','state_id' => 3],
            ['name' => 'Rómulo Gallegos (Elorza)','state_id' => 3],
            ['name' => 'San Fernando (San Fernando de Apure)','state_id' => 3],
            ['name' => 'Bolívar (San Mateo)','state_id' => 4],
            ['name' => 'Camatagua(Camatagua)','state_id' => 4],
            ['name' => 'Francisco Linares Alcántara (Santa Rita)','state_id' => 4],
            ['name' => 'Girardot (Maracay)','state_id' => 4],
            ['name' => 'José Ángel Lamas (Santa Cruz)','state_id' => 4],
            ['name' => 'José Félix Ribas (La Victoria)','state_id' => 4],
            ['name' => 'José Rafael Revenga (El Consejo)','state_id' => 4],
            ['name' => 'Libertador (Palo Negro)','state_id' => 4],
            ['name' => 'Mario Briceño Iragorry (El Limón)','state_id' => 4],
            ['name' => 'Ocumare de la Costa de Oro (Ocumare de la Costa)','state_id' => 4],
            ['name' => 'San Casimiro (San Casimiro)','state_id' => 4],
            ['name' => 'San Sebastián (San Sebastián de los Reyes)','state_id' => 4],
            ['name' => 'Santiago Mariño (Turmero)','state_id' => 4],
            ['name' => 'Santos Michelena (Las Tejerías)','state_id' => 4],
            ['name' => 'Sucre (Cagua)','state_id' => 4],
            ['name' => 'Tovar (Colonia Tovar)','state_id' => 4],
            ['name' => 'Urdaneta (Barbacoas)','state_id' => 4],
            ['name' => 'Zamora (Villa de Cura)','state_id' => 4],
            ['name' => 'Alberto Arvelo Torrealba (Sabaneta)','state_id' => 5],
            ['name' => 'Andrés Eloy Blanco (El Cantón)','state_id' => 5],
            ['name' => 'Antonio José de Sucre (Socopó)','state_id' => 5],
            ['name' => 'Arismendi (Arismendi)','state_id' => 5],
            ['name' => 'Barinas (Barinas)','state_id' => 5],
            ['name' => 'Bolívar (Barinitas)','state_id' => 5],
            ['name' => 'Cruz Paredes (Barrancas)','state_id' => 5],
            ['name' => 'Ezequiel Zamora (Santa Bárbara)','state_id' => 5],
            ['name' => 'Obispos (Obispos)','state_id' => 5],
            ['name' => 'Pedraza (Ciudad Bolivia)','state_id' => 5],
            ['name' => 'Rojas (Libertad)','state_id' => 5],
            ['name' => 'Sosa (Ciudad de Nutrias)','state_id' => 5],
            ['name' => 'Caroní (Ciudad Guayana)','state_id' => 6],
            ['name' => 'Cedeño (Caicara del Orinoco)','state_id' => 6],
            ['name' => 'El Callao (El Callao)','state_id' => 6],
            ['name' => 'Gran Sabana (Santa Elena de Uairén)','state_id' => 6],
            ['name' => 'Heres (Ciudad Bolívar)','state_id' => 6],
            ['name' => 'Piar (Upata)','state_id' => 6],
            ['name' => 'Raúl Leoni (Ciudad Piar)','state_id' => 6],
            ['name' => 'Roscio (Guasipati)','state_id' => 6],
            ['name' => 'Sifontes (Tumeremo)','state_id' => 6],
            ['name' => 'Sucre (Maripa)','state_id' => 6],
            ['name' => 'Padre Pedro Chen (El Palmar)','state_id' => 6],
            ['name' => 'Bejuma (Bejuma)','state_id' => 7],
            ['name' => 'Carlos Arvelo (Güigüe)','state_id' => 7],
            ['name' => 'Diego Ibarra (Mariara)','state_id' => 7],
            ['name' => 'Guacara (Guacara)','state_id' => 7],
            ['name' => 'Juan José Mora (Morón)','state_id' => 7],
            ['name' => 'Libertador (Tocuyito)','state_id' => 7],
            ['name' => 'Los Guayos (Los Guayos)','state_id' => 7],
            ['name' => 'Miranda (Miranda)','state_id' => 7],
            ['name' => 'Montalbán (Montalbán)','state_id' => 7],
            ['name' => 'Naguanagua (Naguanagua)','state_id' => 7],
            ['name' => 'Puerto Cabello (Puerto Cabello)','state_id' => 7],
            ['name' => 'San Diego (San Diego)','state_id' => 7],
            ['name' => 'San Joaquín (San Joaquín)','state_id' => 7],
            ['name' => 'Valencia (Valencia)','state_id' => 7],
            ['name' => 'Anzoátegui (Cojedes)','state_id' => 8],
            ['name' => 'Falcón (Tinaquillo)','state_id' => 8],
            ['name' => 'Girardot (El Baúl)','state_id' => 8],
            ['name' => 'Lima Blanco (Macapo)','state_id' => 8],
            ['name' => 'Pao de San Juan Bautista (El Pao)','state_id' => 8],
            ['name' => 'Ricaurte (Libertad)','state_id' => 8],
            ['name' => 'Rómulo Gallegos','state_id' => 8],
            ['name' => 'Antonio Díaz Curiapo (Curiapo)','state_id' => 9],
            ['name' => 'Casacoima (Sierra Imataca)','state_id' => 9],
            ['name' => 'Pedernales (Pedernales)','state_id' => 9],
            ['name' => 'Tucupita (Tucupita)','state_id' => 9],
            ['name' => 'Archipiélago Las Aves','state_id' => 10],
            ['name' => 'Archipiélago Los Monjes','state_id' => 10],
            ['name' => 'Archipiélago Los Roques','state_id' => 10],
            ['name' => 'Isla de Aves','state_id' => 10],
            ['name' => 'Isla de Patos','state_id' => 10],
            ['name' => 'Isla La Blanquilla','state_id' => 10],
            ['name' => 'Isla La Orchila','state_id' => 10],
            ['name' => 'Isla La Sola','state_id' => 10],
            ['name' => 'Isla La Tortuga','state_id' => 10],
            ['name' => 'Islas Los Frailes','state_id' => 10],
            ['name' => 'Islas Los Hermanos','state_id' => 10],
            ['name' => 'Islas Los Testigos','state_id' => 10],
            ['name' => 'Libertador (Caracas)','state_id' => 11],
            ['name' => 'Acosta (San Juan de los Cayos)','state_id' => 12],
            ['name' => 'Bolívar (San Luis)','state_id' => 12],
            ['name' => 'Buchivacoa (Capatárida)','state_id' => 12],
            ['name' => 'Cacique Manaure (Yaracal)','state_id' => 12],
            ['name' => 'Carirubana (Punto Fijo)','state_id' => 12],
            ['name' => 'Colina (La Vela de Coro)','state_id' => 12],
            ['name' => 'Dabajuro (Dabajuro)','state_id' => 12],
            ['name' => 'Democracia (Pedregal)','state_id' => 12],
            ['name' => 'Falcón (Pueblo Nuevo)','state_id' => 12],
            ['name' => 'Federación (Churuguara)','state_id' => 12],
            ['name' => 'Jacura (Jacura)','state_id' => 12],
            ['name' => 'Los Taques (Santa Cruz de Los Taques)','state_id' => 12],
            ['name' => 'Mauroa (Mene de Mauroa)','state_id' => 12],
            ['name' => 'Miranda (Santa Ana de Coro)','state_id' => 12],
            ['name' => 'Monseñor Iturriza (Chichiriviche)','state_id' => 12],
            ['name' => 'Palmasola (Palmasola)','state_id' => 12],
            ['name' => 'Petit (Cabure)','state_id' => 12],
            ['name' => 'Píritu (Píritu)','state_id' => 12],
            ['name' => 'San Francisco (Mirimire)','state_id' => 12],
            ['name' => 'Silva (Tucacas)','state_id' => 12],
            ['name' => 'Sucre (La Cruz de Taratara)','state_id' => 12],
            ['name' => 'Tocópero (Tocópero)','state_id' => 12],
            ['name' => 'Unión (Santa Cruz de Bucaral)','state_id' => 12],
            ['name' => 'Urumaco (Urumaco)','state_id' => 12],
            ['name' => 'Zamora (Puerto Cumarebo)','state_id' => 12],
            ['name' => 'Esteros de Camaguan(Camaguan)','state_id' => 13],
            ['name' => 'Chaguaramas(Chaguaramas)','state_id' => 13],
            ['name' => 'El Socorro (El Socorro)','state_id' => 13],
            ['name' => 'Francisco de Miranda (Calabozo)','state_id' => 13],
            ['name' => 'José Félix Ribas (Tucupido)','state_id' => 13],
            ['name' => 'José Tadeo Monagas (Altagracia de Orituco)','state_id' => 13],
            ['name' => 'Juan Germán Roscio (San Juan de Los Morros)','state_id' => 13],
            ['name' => 'Julián Mellado (El Sombrero)','state_id' => 13],
            ['name' => 'Las Mercedes (Las Mercedes)','state_id' => 13],
            ['name' => 'Leonardo Infante (Valle de La Pascua)','state_id' => 13],
            ['name' => 'Pedro Zaraza (Zaraza)','state_id' => 13],
            ['name' => 'Ortíz (Ortíz)','state_id' => 13],
            ['name' => 'San Gerónimo de Guayabal (Guayabal)','state_id' => 13],
            ['name' => 'San José de Guaribe (San José de Guaribe)','state_id' => 13],
            ['name' => 'Santa María de Ipire (Santa María de Ipire)','state_id' => 13],
            ['name' => 'Andrés Eloy Blanco (Sanare)','state_id' => 14],
            ['name' => 'Crespo (Duaca)','state_id' => 14],
            ['name' => 'Iribarren (Barquisimeto)','state_id' => 14],
            ['name' => 'Jiménez (Quibor)','state_id' => 14],
            ['name' => 'Morán (El Tocuyo)','state_id' => 14],
            ['name' => 'Palavecino (Cabudare)','state_id' => 14],
            ['name' => 'Simón Planas (Sarare)','state_id' => 14],
            ['name' => 'Torres (Carora)','state_id' => 14],
            ['name' => 'Urdaneta (Siquisique)','state_id' => 14],
            ['name' => 'Alberto Adriani (El Vigía)','state_id' => 15],
            ['name' => 'Andrés Bello (La Azulita)','state_id' => 15],
            ['name' => 'Antonio Pinto Salinas (Santa Cruz de Mora)','state_id' => 15],
            ['name' => 'Sucre (Lagunillas)','state_id' => 15],
            ['name' => 'Tovar (Tovar)','state_id' => 15],
            ['name' => 'Tulio Febres Cordero (Nueva Bolivia)','state_id' => 15],
            ['name' => 'Zea (Zea)','state_id' => 15],
            ['name' => 'Acevedo (Caucagua)','state_id' => 16],
            ['name' => 'Andrés Bello (San José de Barlovento)','state_id' => 16],
            ['name' => 'Baruta (Baruta)','state_id' => 16],
            ['name' => 'Brión (Higuerote)','state_id' => 16],
            ['name' => 'Buroz (Mamporal)','state_id' => 16],
            ['name' => 'Carrizal (Carrizal)','state_id' => 16],
            ['name' => 'Chacao (Chacao)','state_id' => 16],
            ['name' => 'Cristóbal Rojas (Charallave)','state_id' => 16],
            ['name' => 'El Hatillo (El Hatillo)','state_id' => 16],
            ['name' => 'Guaicaipuro (Los Teques)','state_id' => 16],
            ['name' => 'Independencia (Santa Teresa del Tuy)','state_id' => 16],
            ['name' => 'Lander (Ocumare del Tuy)','state_id' => 16],
            ['name' => 'Los Salias (San Antonio de los Altos)','state_id' => 16],
            ['name' => 'Páez (Río Chico)','state_id' => 16],
            ['name' => 'Paz Castillo (Santa Lucía)','state_id' => 16],
            ['name' => 'Pedro Gual (Cúpira)','state_id' => 16],
            ['name' => 'Plaza (Guarenas)','state_id' => 16],
            ['name' => 'Simón Bolívar (San Francisco de Yare)','state_id' => 16],
            ['name' => 'Sucre (Petare)','state_id' => 16],
            ['name' => 'Urdaneta (Cúa)','state_id' => 16],
            ['name' => 'Zamora (Guatire)','state_id' => 16],    
            ['name' => 'Acosta (San Antonio de Capayacuar)','state_id' => 17],
            ['name' => 'Aguasay (Aguasai)','state_id' => 17],
            ['name' => 'Bolívar','state_id' => 17],
            ['name' => 'Cedeño (Caicara)','state_id' => 17],
            ['name' => 'Ezequiel Zamora (Punta de Mata)','state_id' => 17],
            ['name' => 'Libertador (Temblador)','state_id' => 17],
            ['name' => 'Maturín (Maturín)','state_id' => 17],
            ['name' => 'Piar (Aragua)','state_id' => 17],
            ['name' => 'Punceres (Quiriquire)','state_id' => 17],
            ['name' => 'Santa Bárbara (Santa Bárbara)','state_id' => 17],
            ['name' => 'Sotillo (Barrancas del Orinco)','state_id' => 17],
            ['name' => 'Uracoa (Uracoa)','state_id' => 17],    
            ['name' => 'Antolín del Campo (La Plaza de Paraguachí)','state_id' => 18],
            ['name' => 'Arismendi (La Asunción)','state_id' => 18],
            ['name' => 'Díaz (San Juan Bautista)','state_id' => 18],
            ['name' => 'García (El Valle del Espíritu Santo)','state_id' => 18],
            ['name' => 'Gómez (Santa Ana)','state_id' => 18],
            ['name' => 'Maneiro (Pampatar)','state_id' => 18],
            ['name' => 'Marcano (Juan Griego)','state_id' => 18],
            ['name' => 'Mariño (Porlamar)','state_id' => 18],
            ['name' => 'Península de Macanao (Boca de Río)','state_id' => 18],
            ['name' => 'Tubores (Punta de Piedras)','state_id' => 18],
            ['name' => 'Villalba (San Pedro de Coche)','state_id' => 18],
            ['name' => 'Agua Blanca (Agua Blanca)','state_id' => 19],
            ['name' => 'Araure (Araure)','state_id' => 19],
            ['name' => 'Esteller (Píritu)','state_id' => 19],
            ['name' => 'Guanare (Guanare)','state_id' => 19],
            ['name' => 'Guanarito (Guanarito)','state_id' => 19],
            ['name' => 'Monseñor José Vicenti de Unda (Chabasquén de Unda)','state_id' => 19],
            ['name' => 'Ospino (Ospino)','state_id' => 19],
            ['name' => 'Páez (Acarigua)','state_id' => 19],
            ['name' => 'Papelón (Papelón)','state_id' => 19],
            ['name' => 'San Genaro de Boconoíto (Boconoíto)','state_id' => 19],
            ['name' => 'San Rafael de Onoto (San Rafael de Onoto)','state_id' => 19],
            ['name' => 'Santa Rosalía (El Playón)','state_id' => 19],
            ['name' => 'Sucre (Biscucuy)','state_id' => 19],
            ['name' => 'Turén (Villa Bruzual)','state_id' => 19],
            ['name' => 'Andrés Eloy Blanco (Casanay)','state_id' => 20],
            ['name' => 'Andrés Mata (San José de Aerocuar)','state_id' => 20],
            ['name' => 'Arismendi (Río Caribe)','state_id' => 20],
            ['name' => 'Benítez (El Pilar)','state_id' => 20],
            ['name' => 'Bermúdez (Carúpano)','state_id' => 20],
            ['name' => 'Bolívar (Marigüitar)','state_id' => 20],
            ['name' => 'Cajigal (Yaguaraparo)','state_id' => 20],
            ['name' => 'Cruz Salmerón Acosta (Araya)','state_id' => 20],
            ['name' => 'Libertador (Tunapuy)','state_id' => 20],
            ['name' => 'Mariño (Irapa)','state_id' => 20],
            ['name' => 'Mejía (San Antonio del Golfo)','state_id' => 20],
            ['name' => 'Montes (Cumanacoa)','state_id' => 20],
            ['name' => 'Ribero (Cariaco)','state_id' => 20],
            ['name' => 'Sucre (Cumaná)','state_id' => 20],
            ['name' => 'Valdez (Güiria)','state_id' => 20],
            ['name' => 'Andrés Bello(Cordero)','state_id' => 21],
            ['name' => 'Antonio Rómulo Costa (Las Mesas)','state_id' => 21],
            ['name' => 'Ayacucho (El Colón)','state_id' => 21],
            ['name' => 'Bolívar (San Antonio del Táchira)','state_id' => 21],
            ['name' => 'Cárdenas (Táriba)','state_id' => 21],
            ['name' => 'Córdoba (Santa Ana de Táchira)','state_id' => 21],
            ['name' => 'Fernández Feo (San Rafael del Piñal)','state_id' => 21],
            ['name' => 'Francisco de Miranda (San José de Bolívar)','state_id' => 21],
            ['name' => 'García de Hevia (La Fría)','state_id' => 21],
            ['name' => 'Guásimos (Palmira)','state_id' => 21],
            ['name' => 'Independencia (Capacho Nuevo)','state_id' => 21],
            ['name' => 'Jáuregui (La Grita)','state_id' => 21],
            ['name' => 'José María Vargas (El Cobre)','state_id' => 21],
            ['name' => 'Junín (Rubio)','state_id' => 21],
            ['name' => 'San Judas Tadeo (Umuquena)','state_id' => 21],
            ['name' => 'Libertad (Capacho Viejo)','state_id' => 21],
            ['name' => 'Libertador (Abejales)','state_id' => 21],
            ['name' => 'Lobatera (Lobatera)','state_id' => 21],
            ['name' => 'Michelena (Michelena)','state_id' => 21],
            ['name' => 'Panamericano (Coloncito)','state_id' => 21],
            ['name' => 'Pedro María Ureña (Ureña)','state_id' => 21],
            ['name' => 'Rafael Urdaneta (Delicias)','state_id' => 21],
            ['name' => 'Samuel Dario Maldonado (La Tendida)','state_id' => 21],
            ['name' => 'San Cristóbal (San Cristóbal)','state_id' => 21],
            ['name' => 'Seboruco (Seboruco)','state_id' => 21],
            ['name' => 'Simón Rodríguez (San Simon)','state_id' => 21],
            ['name' => 'Sucre (Queniquea)','state_id' => 21],
            ['name' => 'Torbes (San Josesito)','state_id' => 21],
            ['name' => 'Uribante (Pregonero)','state_id' => 21],
            ['name' => 'Andrés Bello (Santa Isabel)','state_id' => 22],
            ['name' => 'Boconó (Boconó)','state_id' => 22],
            ['name' => 'Bolívar (Sabana Grande)','state_id' => 22],
            ['name' => 'Candelaria (Chejendé)','state_id' => 22],
            ['name' => 'Carache (Carache)','state_id' => 22],
            ['name' => 'Escuque (Escuque)','state_id' => 22],
            ['name' => 'José Felipe Márquez Cañizalez (El Paradero)','state_id' => 22],
            ['name' => 'Juan Vicente Campos Elías (Campo Elías)','state_id' => 22],
            ['name' => 'La Ceiba (Santa Apolonia)','state_id' => 22],
            ['name' => 'Miranda (El Dividive)','state_id' => 22],
            ['name' => 'Pampán (Pampán)','state_id' => 22],
            ['name' => 'Trujillo (Trujillo)','state_id' => 22],
            ['name' => 'Andres Linares (San Lazaro)','state_id' => 22],
            ['name' => 'Pampanito (Pampanito)','state_id' => 22],
            ['name' => 'Vargas (La Guaira)','state_id' => 23],
            ['name' => 'Arístides Bastidas (San Pablo)','state_id' => 24],
            ['name' => 'Bolívar (Aroa)','state_id' => 24],
            ['name' => 'Bruzual (Chivacoa)','state_id' => 24],
            ['name' => 'Cocorote (Cocorote)','state_id' => 24],
            ['name' => 'Independencia (Independencia)','state_id' => 24],
            ['name' => 'Almirante Padilla (El Toro)','state_id' => 25],
            ['name' => 'Baralt (San Timoteo)','state_id' => 25],
            ['name' => 'Cabimas (Cabimas)','state_id' => 25],
            ['name' => 'Catatumbo (Encontrados)','state_id' => 25],
            ['name' => 'Colón (San Carlos del Zulia)','state_id' => 25],
            ['name' => 'Francisco Javier Pulgar (Pueblo Nuevo-El Chivo)','state_id' => 25],
            ['name' => 'Jesús Enrique Losada (La Concepción)','state_id' => 25],
            ['name' => 'Jesús María Semprún (Casigua El Cubo)','state_id' => 25],

];
        
        DB::table('cities')->insert($city);
    }
}

